---
postgres:
  host: localhost
  port: 5432
  user: status
  database: status
  password: # this should be supplied via env. These empty settings still needs to be here to make viper read these env vars.
alertsmtp:
  server: smtp.gmail.com
  port: 587
  user: #this could be supplied via env.
  password: #this should be supplied via env.
general:
  encryptionKey: #this should be supplied via env.